### ISSUE TITLE
Fix Variable name in debug_message

### ISSUE THREAD

**Issue by otisbison** [SecondSonConsulting/Renew#46]
https://github.com/SecondSonConsulting/Renew/blob/952476eceebf97068dd84fb41c8dca0ce3cfd313/Renew.sh#L729

Not sure how to properly format one of these messages..

dialgoExitCode should be dialogExitCode

**Comment by otisbison** [comment]
This isn't a customization issue, it's a problem in the renew.sh file :) The variable name is incorrect

**Comment by SecondSonConsulting** [comment]
ahh, I see, thank you. Not sure how I missed that.

In this case, it only affects logging and not functionality. Appreciate the heads up, I will get it fixed in the next iteration.

-Trevor
--
*If you are in need of remote or on-site support, please email us at ***@***.******@***.***> or call our Help Desk extension at (818)988-5231 x1*

Trevor Sysock | Director of MDM and Cloud Solutions
Second Son Consulting, Inc.
818-988-5231 ext.1 | ***@***.******@***.***>
Apple Certified Technical Coordinator
Apple Certified Support Professional
Member, Apple Consultants Network (ACN)
Box.com<http://Box.com> Certified Professional

On Nov 14, 2022, at 8:56 AM, otisbison ***@***.***> wrote:



This isn't a customization issue, it's a problem in the renew.sh file :) The variable name is incorrect

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSecondSonConsulting%2FRenew%2Fissues%2F46%23issuecomment-1314076040&data=05%7C01%7C%7C080cbeea29234d6d5e6408dac6613861%7C03955d82d26044b8b28120dcda5282a9%7C0%7C0%7C638040418128912500%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nXUD%2FkpDBSoNXhB4r38reZEOuG169TnMjEYsNbGOi4Y%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA35Q7XB6RS5RUOQEIK7LERDWIJVM7ANCNFSM6AAAAAASAAJP64&data=05%7C01%7C%7C080cbeea29234d6d5e6408dac6613861%7C03955d82d26044b8b28120dcda5282a9%7C0%7C0%7C638040418128912500%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=d3C63okJs0TR%2FicmQdpSmr6giC3E7nhJJ%2BDcIlfOHSM%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

Privileged And Confidential Communication. This electronic transmission, and any documents attached hereto, (a) are protected by the Electronic Communications Privacy Act (18 USC §§ 2510-2521), (b) may contain confidential and/or legally privileged information, and (c) are for the sole use of the intended recipient named above. If you have received this electronic message in error, please notify the sender and delete the electronic message. Any disclosure, copying, distribution, or use of the contents of the information received in error is strictly prohibited.

**Comment by BigMacAdmin** [comment]
fixed for next release
